### ISSUE TITLE
Testing & Default CI setup

### ISSUE THREAD

**Issue by Pushplaybang** [Nona-Creative/github-boilerplate#11]
## Scope

Getting everyone on board with CI will mean getting everyone on board with automated testing at some level.  I believe is a critical next step to reducing errors / defects and avoiding the goddam awful regressions that sometimes occur, especially in a team environment.

I'm wondering if there is any CI boilerplate, or at the minimum, some guidelines that we should include here?  Possibly in time, it would be good to have a CI repo with different CI configs for different projects, as we create them.

@ShaunEgan @SkippyZA  - really hoping you'll be up to taking the lead on something like this, in the meantime I'm looking into both circle and snap.  I'm also looking into testing obviously more than i have in the past as i've mentioned, I'm starting with Meteor,  and would like to look at PHP next myself (to get some testing into WP), @JamesGarethSmith - it seemed you have quite a bit of knowledge in this area as well (maybe ruby specific?)

I think at the very least we could : 
- Make suggestions or a mention regarding testing of it in the contribution guide
- make specific mention of our approach to deployment

@Nona-Creative/nonabots please fire at will.

**Comment by ShaunEgan** [comment]
For CI, we are currently using CircleCI. Snap-CI was better, but their user management was so damn terrible that it became a nightmare to add new repositories.

Circle CI tries to infer the build process from the repository (eg, _composer.json_ -> `php` build process). You specify a configuration using a `circle.yml` file in your repositories' root directory. You can see any of the crowdCaster embed projects, the digestor project, and the yazimedia project for a good introduction into how to override any of the steps circle performs. 

As for testing, for JS we have extensive experience with Jasmine, so will obviously recommend that. Preferably set that up to be run through `npm` directly, rather than through grunt/gulp or anything like that, else that tends to cause headaches with CI (come ask for more info). PHP will be phpunit most likely, JUnit for Java if anybody is into that.

**Comment by Pushplaybang** [comment]
awesome - thanks for the input, aiming to get circleCI deployment setup for meteor deployments at the very least.  

anything specific you think we should include in this GitHub boilerplate repository?

**Comment by ShaunEgan** [comment]
No - I don't think there is anything that is really boilerplate in those circleCi scripts, unless the plan is to deploy these apps to Ares (The Kubernetes cluster). 

As for the unit testing, that is language specific.

**Comment by Pushplaybang** [comment]
Cool.
